### ISSUE TITLE
Enter the sc instruction and the client exits

### ISSUE THREAD

**Issue by bbtiger** [Crypnotic/VelocityStaffChat#1]
[18:43:31 INFO]: [connected player] test (/113.111.50.206:38450) has disconnected: Your connection has encountered an error. Try again later.
[18:43:31 ERROR]: [connected player] test (/113.111.50.206:38450): exception encountered
java.lang.IncompatibleClassChangeError: Found interface net.kyori.text.TextComponent, but class was expected
        at me.crypnotic.velocitystaffchat.VelocityStaffChat.execute(VelocityStaffChat.java:111) ~[?:?]
        at com.velocitypowered.proxy.command.VelocityCommandManager.execute(VelocityCommandManager.java:62) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23112.jar:1.0.0-SNAPSHOT (git-742865bf-b112)]
        at com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler.handle(ClientPlaySessionHandler.java:115) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23112.jar:1.0.0-SNAPSHOT (git-742865bf-b112)]
        at com.velocitypowered.proxy.protocol.packet.Chat.handle(Chat.java:77) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23112.jar:1.0.0-SNAPSHOT (git-742865bf-b112)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:112) ~[velocity-proxy-1.0.0-SNAPSHOT-all%23112.jar:1.0.0-SNAPSHOT (git-742865bf-b112)]

**Comment by mdcfe** [comment]
This was fixed in 76764e8d4f281371299fb62c3a95cd438949edc5.
